\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<>>=
positions<-as.data.frame(read.table("/Users/alice/Desktop/projects/heterochromatin/pacbio/HG002_ChrY.fasta.70.dat.positions",header=FALSE)) #HG002_unmapped.fasta.70.dat.positions #HG002_ChrY.fasta.70.dat.positions
colnames(positions)<-c("length","start","end")
@

<<>>=
par(mfrow=c(4,2),cex=1.1)
b<-100
hist(as.numeric(positions$start),breaks=b,main="Position of absolute start in the read",col="gold",xlab="start of repeat")
hist(as.numeric(positions$end),breaks=b,main="Position of absolute end in the read",col="gold",xlab="end of repeat")
hist(positions$start/positions$length,breaks=b,main="Position of relative start in the read",col="cyan",xlab="start/length")
hist(positions$end/positions$length,breaks=b,main="Position of relative end in the read",col="cyan",xlab="end/length")
hist(pmin((positions$length-positions$end),positions$start),breaks=b,main="Distance to the end of the read",col="lightgreen",xlab="pmin((positions$length-positions$end),positions$start")
hist(positions$end-positions$start,breaks=b,main="Length of heterochromatic array",col="pink",xlab="end-start")
hist(as.numeric(positions$length),breaks=b,main="Read lengths",col="tomato",xlab="read lengths")

@

<<position bias>>=
par(mfrow=c(2,2),cex=1.1)
setwd("/Users/alice/Desktop/projects/heterochromatin/pacbio/")
filenames <- list.files(pattern="*.positions", full.names=FALSE)

for (i in (filenames)) {
  positions<-read.table(i,header=FALSE)
  boxplot(positions$V2 ~ positions$V1,col="gold",main=i,ylim=c(0,100))
}


#positions<-read.table("/Users/alice/Desktop/projects/heterochromatin/pacbio/out_HG002.positions",header=FALSE)
#boxplot(positions$V2 ~ positions$V1,col="gold",main="HG002",ylim=c(0,100))
#positions<-read.table("/Users/alice/Desktop/projects/heterochromatin/pacbio/out_HG003.positions",header=FALSE)
#boxplot(positions$V2 ~ positions$V1,col="gold",main="HG003",ylim=c(0,100))
#positions<-read.table("/Users/alice/Desktop/projects/heterochromatin/pacbio/out_PR.positions",header=FALSE)
#boxplot(positions$V2 ~ positions$V1,col="cyan",main="Simulated DYZ PacBio reads at 1000x",ylim=c(0,100))
#positions<-read.table("/Users/alice/Desktop/projects/heterochromatin/pacbio/out_PPR.positions",header=FALSE)
#boxplot(positions$V2 ~ positions$V1,col="cyan",main="Simulated Perfect PacBio reads at 1000x",ylim=c(0,100))
@



\end{document}