\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}


<<analyze merged table>>=
library(plyr)
par(mfrow=c(2,2),cex=1.2)

rep.row <- function(r, n){
  colwise(function(x) rep(x, n))(r)
}

PCRcounts<-as.data.frame(read.table("/Users/polly/Desktop/projects/heterochromatin/PCR/big.table.with.header.rawcounts.sortedFilt.txt",header=TRUE,row.names=1))
PCRlengths<-as.data.frame(read.table("/Users/polly/Desktop/projects/heterochromatin/PCR/big.table.with.header.rawlengths.sortedFilt.txt",header=TRUE,row.names=1))

#PCRcounts<-PCRcounts[complete.cases(PCRcounts), ]
#PCRlengths<-PCRlengths[complete.cases(PCRlengths), ] #transform into repeat density
PCRcounts[is.na(PCRcounts)] <- 0
PCRlengths[is.na(PCRlengths)] <- 0

colnames(PCRcounts)<-c("PCRminus","PCRplus2","PCRplus1")
colnames(PCRlengths)<-c("PCRminus","PCRplus2","PCRplus1")

#normalize by read count
counts<-as.data.frame(cbind(28278372,3587652,94110593))

#PCRcounts<-normalize(PCRcounts,counts)
#PCRlengths<-normalize(PCRlengths,counts)

normalization_factor=1000000

normalization_matrix<-rep.row(counts,nrow(PCRcounts))
PCRcounts<-PCRcounts/normalization_matrix*normalization_factor #normalization of data by read counts

normalization_matrix<-rep.row(counts,nrow(PCRlengths))
PCRlengths<-PCRlengths/normalization_matrix*normalization_factor #normalization of data by read counts

PCRcounts<-PCRcounts[order(rowSums(PCRcounts),decreasing=T),]
PCRlengths<-PCRlengths[order(rowSums(PCRlengths),decreasing=T),]

#PCRlengths<-PCRlengths/150 #originally bp per 1 million reads; since 1 million reads is 150,000,000 bps, after read length adjustment, bp per Mb
#PCRlengths<-PCRlengths/1000 #report in kb/Mb
print(head(PCRcounts))
print(head(PCRlengths))


#COUNTS
limit<-max(PCRcounts)
plot(PCRcounts$PCRplus1,PCRcounts$PCRplus2,col="red",xlim=c(0,limit),ylim=c(0,limit),main="correspondence between technical replicates",xlab="PCR+, replicate1",ylab="PCR+, replicate2",sub="Counts per 1 million reads")
abline(a=c(0,0),b=(1),col="gray")

plot(PCRcounts$PCRminus,PCRcounts$PCRplus1,col="red",xlim=c(0,limit),ylim=c(0,limit),main="PCR+ repeat counts are overrepresented",xlab="PCR-, control",ylab="PCR+, replicate 1",sub="Counts per 1 million reads")
abline(a=c(0,0),b=(1),col="gray")

plot(PCRcounts$PCRminus,PCRcounts$PCRplus1,col="red",xlim=c(0,limit),ylim=c(0,limit),main="PCR+ repeat counts are overrepresented",xlab="PCR-, control",ylab="PCR+, replicate 2",sub="Counts per 1 million reads")
abline(a=c(0,0),b=(1),col="gray")

plus1_minus<-lm((PCRcounts$PCRplus1-PCRcounts$PCRminus) ~ 0) #residuals tell us how much to correct
res_vs_counts<-lm(resid(plus1_minus)~PCRcounts$PCRplus1)
slope<-as.numeric(coef(res_vs_counts)[2]) #slope for the correction

plot(PCRcounts$PCRminus,PCRcounts$PCRplus1-slope*PCRcounts$PCRplus1,xlim=c(0,limit),ylim=c(0,limit),main="linear relationship after correction",xlab="PCR-",ylab="CORRECTED PCR+, replicate 1",col="red")
abline(a=c(0,0),b=(1),col="gray")


#DENSITIES
limit<-max(PCRlengths)
plot(PCRlengths$PCRplus1,PCRlengths$PCRplus2,col="blue",xlim=c(0,limit),ylim=c(0,limit),main="correspondence between technical replicates",xlab="PCR+, replicate1",ylab="PCR+, replicate2",sub="Repeat density")
abline(a=c(0,0),b=(1),col="gray")

plot(PCRlengths$PCRminus,PCRlengths$PCRplus1,col="blue",xlim=c(0,limit),ylim=c(0,limit),main="PCR+ repeat densities are overrepresented",xlab="PCR-, control",ylab="PCR+, replicate 1",sub="Repeat density")
abline(a=c(0,0),b=(1),col="gray")

plot(PCRlengths$PCRminus,PCRlengths$PCRplus1,col="blue",xlim=c(0,limit),ylim=c(0,limit),main="PCR+ repeat densities are overrepresented",xlab="PCR-, control",ylab="PCR+, replicate 2",sub="Repeat density")
abline(a=c(0,0),b=(1),col="gray")

plus1_minus<-lm((PCRlengths$PCRplus2-PCRlengths$PCRminus) ~ 0) #residuals tell us how much to correct
res_vs_densities<-lm(resid(plus1_minus)~PCRlengths$PCRplus2)
slope<-as.numeric(coef(res_vs_densities)[2]) #slope for the correction

plot(PCRlengths$PCRminus,PCRlengths$PCRplus1-slope*PCRlengths$PCRplus1,xlim=c(0,limit),ylim=c(0,limit),main="linear relationship after correction",xlab="PCR-",ylab="CORRECTED PCR+, replicate 1",col="blue")
abline(a=c(0,0),b=(1),col="gray")




@

\end{document}