\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<>>=
file<-"/Users/alice/Desktop/projects/heterochromatin/32mers/out_ATCTGTATGAACATGGAAATATCTACACCGCT_C2+C3_1mil.fasta.positions"
positions<-as.data.frame(read.table(file,header=FALSE)) 
#HG002_unmapped.fasta.70.dat.positions #HG002_ChrY.fasta.70.dat.positions
#/Users/alice/Desktop/projects/heterochromatin/pacbio/HG002_ChrY.fasta.70.dat.positions
colnames(positions)<-c("length","start","end")

plotRepeatDistribution(file,positions)
@

<<>>=


plotRepeatDistribution <- function(file, positions) {
  par(mfrow = c(2, 2), cex = 1.1)
  label=gsub(".fasta.positions", "", gsub("out_", "", basename(file)))
  b <- 100
  #hist(as.numeric(positions$start),breaks=b,main="Position of absolute start in the read",col="gold",xlab="start of repeat")
  #hist(as.numeric(positions$end),breaks=b,main="Position of absolute end in the read",col="gold",xlab="end of repeat")
  hist(
    positions$start / positions$length,
    breaks = b,
    main = "Position of relative start in the read",
    col = "cyan",
    xlab = "start/length",
    xlim = c(0, 1),
    sub = label
  )
  hist(
    positions$end / positions$length,
    breaks = b,
    main = "Position of relative end in the read",
    col = "cyan",
    xlab = "end/length",
    xlim = c(0, 1),
    sub = label
  )
  #hist(pmin((positions$length-positions$end),positions$start),breaks=b,main="Distance to the end of the read",col="lightgreen",xlab="pmin((positions$length-positions$end),positions$start")
  hist(
    positions$end - positions$start,
    breaks = b,
    main = "Length of heterochromatic array",
    col = "pink",
    xlab = "end-start",
    sub = label
  )
  hist(
    as.numeric(positions$length),
    breaks = b,
    main = "Read lengths",
    col = "tomato",
    xlab = "read lengths",
    sub = label
  )
}
@

<<position bias>>=
par(mfrow=c(2,2),cex=1.1)
setwd("/Users/alice/Desktop/projects/heterochromatin/pacbio/")
filenames <- list.files(pattern="*.positions", full.names=FALSE)

for (file in (filenames)) {
tryCatch({
        if (file.size(file) > 0){
        data<-read.table(file, header = F)
        boxplot(data$V2 ~ data$V1,col="gold",main=file,ylim=c(0,100))
           }
        }, error = function(err) {
            # error handler picks up where error was generated
            print(paste("Read.table didn't work!:  ",err))
        })
}

@

<<first matches>>=
par(mfrow=c(2,2),cex=1.5)
setwd("/Users/alice/Desktop/projects/heterochromatin/pacbio/")
filenames <- list.files(pattern="*HG003.GGAAT", full.names=FALSE)

for (file in (filenames)) {
tryCatch({
        if (file.size(file) > 0){
        data<-as.data.frame(read.table(file, header = F))
        plot(data$V2/1000,col="blue",sub=file,pch=16,cex=1.2,xlab="order",ylab="count in thousands")
        mtext(data$V1,srt=90,side=3,at=1:10,las=3,col="blue")
           }
        }, error = function(err) {
            # error handler picks up where error was generated
            print(paste("Read.table didn't work!:  ",err))
        })
}

@

\end{document}